#!/bin/sh

# ------------------------------------------------------
# file:     $HOME/.scripts/dzenstat.sh
# author:   Ramon Solis - http://cyb3rpunk.wordpress.com
# modified: June 2011
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
# ------------------------------------------------------

# -------------------------
# Dzen settings & Variables
# -------------------------
ICONPATH="$HOME/.xbm/"
CRIT_COLOR="#BA4040"
COLOR_ICON="#f36c60"
DZEN_FG="#ffffff"
DZEN_BG="#263238"
HEIGHT=26
WIDTH=1190
RESOLUTIONW=1920
RESOLUTIONH=1080
X=660
Y=1060
#BAR_FG="#1E90FF"
BAR_FG="#268BD2"
BAR_BG="#FFFFFF"
SEPERATOR="ffff00"
BAR_H=10
BAR_W=80
FONT="-*-Inconsolata-medium-r-*-*-15-*-*-*-*-*-iso10646-*"
SLEEP=1
VUP="amixer -c0 -q set Master 4dB+"
VDOWN="amixer -c0 -q set Master 4dB-"
EVENT="button3=exit;button4=exec:$VUP;button5=exec:$VDOWN"
DZEN="dzen2 -x $X -y $Y -w $WIDTH -h $HEIGHT -fn $FONT -ta right -bg $DZEN_BG -fg $DZEN_FG -e "button3=exit;button4=exec:$VUP;button5=exec:$VDOWN""

# -------------
# Infinite loop
# -------------
while :; do
sleep ${SLEEP}

# ---------
# Functions
# ---------
Window ()
{
    NAME=$(xdotool getactivewindow getwindowname| cut -c1-50)
    echo -n " ${NAME}"
    return
}

CPU ()
{
    CPU=$( grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')
    echo -n " ^fg($COLOR_ICON)^i($ICONPATH/cpu.xbm) ^fg()" $(echo $CPU | gdbar -fg $BAR_FG -bg $BAR_BG -h $BAR_H -w $BAR_W -s o -ss 0 -sw 2 -nonl )
}

Vol ()
{
	ONF=$(amixer get Master | awk '/Front\ Left:/ {print $7}' | tr -d '[]')
	VOL=$(amixer get Master | awk '/Front\ Left:/ {print $5}' | tr -d '[]%')
		if [[ ${ONF} == 'off' ]] ; then
		   echo -n "^fg($CRIT_COLOR)^i($ICONPATH/spkr_01.xbm)^fg()" $(echo "0"  | gdbar -fg "#DEDEDE" -bg $BAR_BG -h $BAR_H -w $BAR_W -s o -ss 1 -sw 2 -nonl)
		else
		   echo -n "^fg($COLOR_ICON)^i($ICONPATH/spkr_01.xbm)^fg()"  $(echo $VOL | gdbar -fg $BAR_FG -bg $BAR_BG -max 155  -h $BAR_H -w $BAR_W -s o -ss 0 -sw 2 -nonl)
		fi
    return
}

Mem ()
{
	MEM=$(free -m | grep '-' | awk '{print $3}')
	echo -n "^fg($COLOR_ICON)^i($ICONPATH/mem.xbm)^fg()" $(echo $MEM | gdbar -fg $BAR_FG  -bg $BAR_BG -h $BAR_H -max 8192 -s o  -w $BAR_W  -sw 2 -ss 0 -nonl )
	return
}

Temp ()
{
	TEMP=$(acpi -t | awk '{print $4}' | tr -d '.0')
		if [[ ${TEMP} -gt 63 ]] ; then
			echo -n "^fg($CRIT_COLOR)^i($ICONPATH/temp.xbm)^fg($CRIT_COLOR) ${TEMP}°C" $(echo ${TEMP} | gdbar -fg $CRIT_COLOR -bg $BAR_BG -h $BAR_H -s v -sw 5 -ss 0 -sh 1 -nonl)
		else
			echo -n "^fg($COLOR_ICON)^i($ICONPATH/temp.xbm)^fg() ${TEMP}°C" $(echo ${TEMP} | gdbar -fg $BAR_FG -bg $BAR_BG -h $BAR_H -s v -sw 5 -ss 0 -sh 1 -nonl)
		fi
	return
}

Battery ()
{
  BAT=$(acpi | grep -o '[0-9]*%')
  CHARGE=$(acpi | cut -c 12)
  if [[ ${CHARGE} == 'C' ]] ; then
  echo -n "^ca(1, ~/Dzen2/dzen-configs/strangeWORLD/battery-state.sh )^fg($COLOR_ICON)^i($ICONPATH/power-ac.xbm)^fg() ${BAT} " $(echo $BAT | gdbar -fg "#27ae60" -h 16 -max 98  -s v -sw 10 -ss 0 -sh 1 -nonl)
  else
  if [[ ${CHARGE} == 'F' ]] ; then
  echo -n "^ca(1, ~/Dzen2/dzen-configs/strangeWORLD/battery-state.sh )^fg(#27AE60)^i($ICONPATH/power-ac.xbm)^fg(#FFFFFF) ${BAT} "
  else
  echo -n "^ca(1, ~/Dzen2/dzen-configs/strangeWORLD/battery-state.sh )^fg($COLOR_ICON)^i($ICONPATH/bat_full_02.xbm)^fg() ${BAT}" $(echo $BAT | gdbar -fg "#DC322F" -h 16 -max 98  -s v -sw 10  -ss 0 -sh 1 -nonl)
  fi
  fi
  echo -n "^ca()"
  return
}

Ip ()
{
    IP=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}')
    echo -n  "^fg($COLOR_ICON)^i($ICONPATH/link.xbm) ^fg()${IP} "
    return
}

Date ()
{
	TIME=$(date +%R)
  echo -n "^ca(1, ~/Dzen2/dzen-configs/strangeWORLD/time-date.sh)^fg($COLOR_ICON)^i($ICONPATH/clock.xbm)^fg() ${TIME}^ca()"
	return
}

Between ()
{
    echo -n " ^fg($SEPERATOR)^r(2x5)^fg() "
	return
}

OSLogo ()
{
	echo -n " ^fg($COLOR_ICON)^i($ICONPATH/gentoo.xbm)^fg()"
	return
}

Wifi ()
{
	echo -n " ^fg($COLOR_ICON)^i($ICONPATH/wifi_02.xbm)^fg()"
	return
}


# --------- End Of Functions

# -----
# Print
# -----
Print () {
    Window
        Between
		OSLogo
        Between
    CPU
        Between
    Mem
        Between
    Ip
        Between
    Vol
        Between
    Battery
        Between
    Date
        echo
    return
}

echo "$(Print)"
#done
done | $DZEN &
