#!/bin/sh

# ------------------------------------------------------
# file:     $HOME/.scripts/dzenstat.sh
# author:   Ramon Solis - http://cyb3rpunk.wordpress.com
# modified: June 2011
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
# ------------------------------------------------------

# -------------------------
# Dzen settings & Variables
# -------------------------
ICONPATH="$HOME/.xbm/"
COLOR_ICON="#6e9bcf"
CRIT_COLOR="#ff2c4a"
DZEN_FG="#a0a0a0"
DZEN_BG="#1f1f1f"
HEIGHT=25
WIDTH=1190
RESOLUTIONW=1920
RESOLUTIONH=1080
X=660
Y=1060
BAR_FG="#ffffff"
BAR_BG="#808080"
BAR_H=10
BAR_W=80
FONT="-*-terminus-medium-r-*-*-15-*-*-*-*-*-iso10646-*"
SLEEP=1
VUP="amixer -c0 -q set Master 4dB+"
VDOWN="amixer -c0 -q set Master 4dB-"
EVENT="button3=exit;button4=exec:$VUP;button5=exec:$VDOWN"
DZEN="dzen2 -x $X -y $Y -w $WIDTH -h $HEIGHT -fn $FONT -ta right -bg $DZEN_BG -fg $DZEN_FG -e "button3=exit;button4=exec:$VUP;button5=exec:$VDOWN""

# -------------
# Infinite loop
# -------------
while :; do
sleep ${SLEEP}

# ---------
# Functions
# ---------
Window ()
{
    NAME=$(xdotool getactivewindow getwindowname| cut -c1-30)
    echo -n " ^fg($COLOR_ICON)^i($ICONPATH/corner.xbm)^fg() ${NAME}"
    return
}

CPU ()
{
    CPU=$( grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')
    echo -n " ^fg($COLOR_ICON)^i($ICONPATH/cpu.xbm) ^fg()" $(echo $CPU | gdbar -fg "#aef8ef" -h $BAR_H -w $BAR_W -s o -ss 0 -sw 2 -nonl )
}

Vol ()
{
	ONF=$(amixer get Master | awk '/Front\ Left:/ {print $7}' | tr -d '[]')
	VOL=$(amixer get Master | awk '/Front\ Left:/ {print $5}' | tr -d '[]%')
		if [[ ${ONF} == 'off' ]] ; then
		   echo -n "^fg($CRIT_COLOR)^i($ICONPATH/spkr_01.xbm)^fg()" $(echo "0"  | gdbar -fg "#DEDEDE" -bg $BAR_BG -h $BAR_H -w $BAR_W -s o -ss 1 -sw 2 -nonl)
		else
		   echo -n "^fg($COLOR_ICON)^i($ICONPATH/spkr_01.xbm)^fg()" ${VOL} $(echo $VOL | gdbar -fg "#00BCD4" -bg $BAR_BG -h $BAR_H -w $BAR_W -s o -ss 0 -sw 2 -nonl)
		fi
    return
}

Mem ()
{
	MEM=$(free -m | grep '-' | awk '{print $3}')
	echo -n "^fg($COLOR_ICON)^i($ICONPATH/mem.xbm)^fg()" $(echo $MEM | gdbar -fg $CRIT_COLOR -bg $BAR_BG -h $BAR_H -max 8192 -s o  -w $BAR_W  -sw 2 -ss 0 -nonl )
	return
}

Temp ()
{
	TEMP=$(acpi -t | awk '{print $4}' | tr -d '.0')
		if [[ ${TEMP} -gt 63 ]] ; then
			echo -n "^fg($CRIT_COLOR)^i($ICONPATH/temp.xbm)^fg($CRIT_COLOR) ${TEMP}°C" $(echo ${TEMP} | gdbar -fg $CRIT_COLOR -bg $BAR_BG -h $BAR_H -s v -sw 5 -ss 0 -sh 1 -nonl)
		else
			echo -n "^fg($COLOR_ICON)^i($ICONPATH/temp.xbm)^fg() ${TEMP}°C" $(echo ${TEMP} | gdbar -fg $BAR_FG -bg $BAR_BG -h $BAR_H -s v -sw 5 -ss 0 -sh 1 -nonl)
		fi
	return
}

Battery ()
{
	BAT=$(acpi | awk '{print $4}' | cut -c 1,2)
  CHARGE=$(acpi | cut -c 12)
  if [[ ${CHARGE} == 'C' ]] ; then
  echo -n "^fg($COLOR_ICON)^i($ICONPATH/power-ac.xbm)^fg() ${BAT}% " $(echo $BAT | gdbar -fg "#8EE38B" -bg $BAR_BG -h 10  -s v -sw 5  -ss 0 -sh 1 -nonl)
  else
  echo -n "^fg($COLOR_ICON)^i($ICONPATH/power-bat.xbm)^fg() ${BAT}%" $(echo $BAT | gdbar -fg "#D14238"  -bg $BAR_BG -h 10  -s v -sw 5  -ss 0 -sh 1 -nonl)
  fi
  return
}

Ip ()
{
    IP=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}')
    echo -n  "^fg(#aeee00)^i($ICONPATH/link.xbm) ^fg()${IP} "
    return
}

Date ()
{
	TIME=$(date +%R)
  echo -n "^fg($COLOR_ICON)^i($ICONPATH/clock.xbm)^fg() ${TIME}"
	return
}

Between ()
{
    echo -n " ^fg(#7298a9)^r(2x2)^fg() "
	return
}

OSLogo ()
{
	echo -n " ^fg(#b16286)^i($ICONPATH/gentoo.xbm)^fg()"
	return
}
# --------- End Of Functions

# -----
# Print
# -----
Print () {
    Window
        Between
		OSLogo
        Between
    CPU
        Between
        Mem
        Between
        Ip
        Between
        Vol
        Between
        Battery
        Between
        Date
        echo
    return
}

echo "$(Print)"
#done
done | $DZEN &
