#!/bin/sh
base03=#002b36
base02=#073642
base01=#586e75
base00=#657b83
base0=#839496
base1=#93a1a1
base2=#eee8d5
base3=#fdf6e3
yellow=#b58900
orange=#cb4b16
red=#dc322f
magenta=#d33682
violet=#6c71c4
blue=#268bd2
cyan=#2aa198
green=#859900
CACHE=${XDG_CACHE_HOME:-"~/.cache"}/dmenu_run
(
        IFS=:
        if test "`ls -dt $PATH "$CACHE" 2> /dev/null | sed 1q`" != "$CACHE"; then
                mkdir -p "`dirname "$CACHE"`" && lsx $PATH | sort -u > "$CACHE"
        fi
)
exe=`dmenu_run -p ">>"   -fn 'Terminus-9:normal' -nb $base03 -nf $base0 -sb $base02 -sf $magenta "$@"< "$CACHE"` && exec sh -c "$exe"









#exec dmenu_run -fn 'DejaVu Sans Mono 8' -nb $base03 -nf $base0 -sb $base02 -sf $magenta "$@"
